name: Build and Preview

on:
  pull_request:
    branches:
      - main  
    paths:
      - "frontend/**"
env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      preview_url: ${{ steps.deploy-preview.outputs.preview_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Install Tailwind CSS and dependencies
        run: |
          cd frontend
          npm install -D tailwindcss postcss autoprefixer
          npm rebuild @tailwindcss/oxide

      - name: Build project
        run: |
          cd frontend
          npm run build

      - name: Cache Next.js build
        uses: actions/cache@v4
        with:
          path: |
            frontend/.next/cache
            frontend/node_modules
          key: ${{ runner.os }}-nextjs-${{ hashFiles('frontend/package-lock.json') }}

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel Preview
        id: deploy-preview
        run: |
          PREVIEW_URL=$(vercel deploy --token="${{ secrets.VERCEL_TOKEN }}" --yes)
          echo "preview_url=$PREVIEW_URL" >> $GITHUB_OUTPUT
          echo "✅ Preview deployment completed successfully!"
          echo "🔗 Preview URL: $PREVIEW_URL"
        

      - name: Comment on PR with Preview URL
        uses: actions/github-script@v6
        with:
          script: |
            const previewUrl = "${{ steps.deploy-preview.outputs.preview_url }}";
            if (previewUrl) {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `✅ Preview deployment is ready! \n\n🔗 [Preview URL](${previewUrl})`
              });
            }